var umol_autocomplete_data = [
{value: "/degrees/online-blended-degree-second-bachelor-accelerated-nursing-dartmouth", label: "Accelerated Second Bachelor of Science in Nursing"},
{value: "/degrees/online-certificate-alcoholism-chemical-dependency-treatment", label: "Addictions Counselor Education Programs Certificate"},
{value: "/degrees/online-certificate-arts-management", label: "Arts Management Certificate Program"},
{value: "/degrees/online-degree-associates-science-business-administration", label: "Associate of Science in Business Administration"},
{value: "/degrees/online-degree-associates-information-technology", label: "Associate of Science in Information Technology"},
{value: "/degrees/online-associate-sustainable-food-farming", label: "Associate of Science in Sustainable Food and Farming"},
{value: "/degrees/online-degree-bachelor-advocacy-social-justice-studies", label: "BA, Advocacy and Social Justice Studies Concentrations"},
{value: "/degrees/online-degree-bachelor-applied-psychology", label: "BA, Applied Psychology Concentrations"},
{value: "/degrees/online-degree-bachelor-arts-administration", label: "BA, Arts Management Concentrations"},
{value: "/degrees/online-degree-bachelor-business", label: "BA, Business Studies Concentrations"},
{value: "/degrees/online-degree-bachelors-children-learning-development", label: "BA, Children's Learning and Development Concentrations"},
{value: "/degrees/online-degree-bachelor-criminal-justice", label: "BA, Criminal Justice Concentrations"},
{value: "/degrees/online-degree-bachelor-early-care-childhood", label: "BA, Early Childhood Education Concentrations"},
{value: "/degrees/online-degree-film-media-studies-concentrations", label: "BA, Film and Media Studies Concentrations"},
{value: "/degrees/online-degree-bachelor-health-studies", label: "BA, Health Studies Concentrations"},
{value: "/degrees/online-degree-bachelor-human-services", label: "BA, Human Services Concentrations"},
{value: "/degrees/online-degree-bachelor-of-arts", label: "BA, Individualized Concentrations"},
{value: "/degrees/online-degree-bachelor-journalism", label: "BA, Journalism Studies Concentrations"},
{value: "/degrees/online-degree-bachelor-liberal-arts-concentrations", label: "BA, Liberal Arts Concentrations"},
{value: "/degrees/online-degree-bachelor-sustainable-studies", label: "BA, Sustainability Studies Concentrations"},
{value: "/degrees/online-degree-bachelor-translation-interpretation", label: "BA, Translation and Interpreting Concentrations"},
{value: "/degrees/online-degree-bachelor-writing", label: "BA, Writing Concentrations"},
{value: "/degrees/online-blended-bachelor-crime-justice-studies", label: "Bachelor of Arts in Crime and Justice Studies"},
{value: "/degrees/online-bachelor-economics", label: "Bachelor of Arts in Economics"},
{value: "/degrees/online-bachelor-economics-healthcare-services-administration", label: "Bachelor of Arts in Economics with Healthcare Services Administration Concentration"},
{value: "/degrees/online-degree-bachelor-arts-english", label: "Bachelor of Arts in English"},
{value: "/degrees/online--bachelor-english-literature-criticism", label: "Bachelor of Arts in English with Literature and Criticism option"},
{value: "/degrees/online-degree-bachelor-global-affairs", label: "Bachelor of Arts in Global Affairs"},
{value: "/degrees/online-blended-bachelor-history", label: "Bachelor of Arts in History"},
{value: "/degrees/online-degree-bachelor-psychology", label: "Bachelor of Arts in Psychology"},
{value: "/degrees/online-bachelor-arts-public-administration", label: "Bachelor of Arts in Public Administration"},
{value: "/degrees/online-blended-bachelor-sociology-anthropology", label: "Bachelor of Arts in Sociology and Anthropology"},
{value: "/degrees/online-degree-bachelor-business-administration", label: "Bachelor of Business Administration"},
{value: "/degrees/online-degree-bachelor-business-administration-lowell", label: "Bachelor of Business Administration - UMass Lowell"},
{value: "/degrees/online-degree-liberal-arts-degree-completion", label: "Bachelor of Liberal Arts, Online Degree Program"},
{value: "/degrees/online-degree-bachelor-liberal-arts", label: "Bachelor of Liberal Arts, Online Degree Program - UMass Lowell"},
{value: "/degrees/online-blended-bachelor-accounting", label: "Bachelor of Science in Accounting"},
{value: "/degrees/online-degree-bachelor-criminal-justice-lowell", label: "Bachelor of Science in Criminal Justice"},
{value: "/degrees/online-bachelor-science-finance", label: "Bachelor of Science in Finance"},
{value: "/degrees/online-degree-bachelor-general-business-administration", label: "Bachelor of Science in General Business Administration"},
{value: "/degrees/online-degree-bachelor-hospitality-tourism-management", label: "Bachelor of Science in Hospitality and Tourism Management"},
{value: "/degrees/online-degree-bachelor-information-technology", label: "Bachelor of Science in Information Technology"},
{value: "/degrees/online-degree-bachelor-information-technology-business", label: "Bachelor of Science in Information Technology: Business Minor"},
{value: "/degrees/online-degree-second-bachelor-information-technology", label: "Bachelor of Science in Information Technology: Second Degree"},
{value: "/degrees/online-bachelor-management-leadership", label: "Bachelor of Science in Management - Leadership Option"},
{value: "/degrees/online-bachelor-science-management-information-systems-ecommerce-digital-business", label: "Bachelor of Science in Management Information Systems - E-Commerce/Digital Business"},
{value: "/degrees/online-bachelor-science-management-information-systems-technology-management", label: "Bachelor of Science in Management Information Systems - Technology & Management"},
{value: "/degrees/online-bachelor-marketing", label: "Bachelor of Science in Marketing"},
{value: "/degrees/online-degree-bachelor-medical-laboratory-science-clinical", label: "Bachelor of Science in Medical Laboratory Science (MLT - MLS)"},
{value: "/degrees/online-bachelor-operations-management", label: "Bachelor of Science in Operations Management"},
{value: "/degrees/online-bachelor-science-public-administration", label: "Bachelor of Science in Public Administration"},
{value: "/degrees/online-bachelor-sustainable-food-farming", label: "Bachelor of Science in Sustainable Food and Farming"},
{value: "/degrees/online-certificate-business-foundations-dartmouth", label: "Business Foundations Graduate Certificate"},
{value: "/programs/subject/1025-business-management", label: "Business Management"},
{value: "/degrees/online-blended-certificate-accounting", label: "Certificate in Accounting"},
{value: "/degrees/online-degree-certificate-accounting-lowell", label: "Certificate in Accounting - UMass Lowell"},
{value: "/degrees/online-arts-management-certificate", label: "Certificate in Arts Management Program"},
{value: "/degrees/online-certificate-general-business-studies", label: "Certificate in Business Studies"},
{value: "/degrees/online-certificate-computer-assisted-manufacturing", label: "Certificate in Computer Assisted Manufacturing"},
{value: "/degrees/online-certificate-computer-science", label: "Certificate in Computer Science"},
{value: "/degrees/online-certificate-contemporary-communications", label: "Certificate in Contemporary Communications"},
{value: "/degrees/online-certificate-data-telecommunications", label: "Certificate in Data/Telecommunications"},
{value: "/degrees/online-certificate-film-studies", label: "Certificate in Film Studies"},
{value: "/degrees/online-certificate-graphics-design-digital-imaging", label: "Certificate in Graphic Design and Digital Imaging"},
{value: "/degrees/online-certificate-human-resource-management", label: "Certificate in Human Resource Management"},
{value: "/degrees/online-certificate-information-technology", label: "Certificate in Information Technology"},
{value: "/degrees/online-certificate-instructional-technology-design", label: "Certificate in Instructional and Technology Design"},
{value: "/degrees/online-certificate-java-development", label: "Certificate in Java Development"},
{value: "/degrees/online-certificate-event-management", label: "Certificate in Meeting and Event Management"},
{value: "/degrees/online-certificate-multimedia-applications", label: "Certificate in Multimedia Applications"},
{value: "/degrees/online-certificate-paralegal-studies", label: "Certificate in Paralegal Studies"},
{value: "/degrees/online-certificate-homeland-security-management", label: "Certificate in Security Management and Homeland Security"},
{value: "/degrees/online-certificate-sustainable-business-practice", label: "Certificate in Sustainable Business Practice"},
{value: "/degrees/online-certificate-sustainable-food-farming", label: "Certificate in Sustainable Food and Farming"},
{value: "/degrees/online-certificate-translation-interpreting", label: "Certificate in Translation and Interpreting"},
{value: "/degrees/online-certificate-unix", label: "Certificate in UNIX/Linux Operating Systems"},
{value: "/degrees/online-certificate-website-design-development", label: "Certificate in Website Design and Development"},
{value: "/degrees/online-certificate-journalism", label: "Certificate of Journalism"},
{value: "/degrees/online-certificate-digital-marketing", label: "Certificate Program in Digital Marketing"},
{value: "/degrees/online-certificate-spanish-english-translation", label: "Certificate Program in Spanish-English Translation"},
{value: "/degrees/online-courses-continuing-medical-education", label: "CME/CEU Courses"},
{value: "/programs/subject/1073-computing-and-information-technology", label: "Computing and Information Technology"},
{value: "/degrees/blended-degree-concurrent-dietetic-internship-master-public-health-nutrition", label: "Concurrent Dietetic Internship/Online Master of Public Health in Nutrition Program (DI/MPH-N)"},
{value: "/programs/subject/1074-criminal-justice-and-legal", label: "Criminal Justice and Legal"},
{value: "/degrees/online-certificate-criminal-justice", label: "Criminal Justice Studies Certificate"},
{value: "/degrees/online-certificate-critical-creative-thinking", label: "Critical and Creative Thinking"},
{value: "/degrees/online-degree-doctor-education-leadership-schooling", label: "Doctor of Education in Leadership in Schooling, Ed.D"},
{value: "/degrees/online-degree-doctor-education-leadership-schooling-stem", label: "Doctor of Education in Leadership in Schooling: STEM Option, Ed.D"},
{value: "/degrees/online-doctor-nursing-practice", label: "Doctor of Nursing Practice (Amherst)"},
{value: "/degrees/online-post-masters-doctor-of-nursing", label: "Doctor of Nursing Practice (Boston)"},
{value: "/programs/subject/41-education", label: "Education"},
{value: "/degrees/online-degree-masters-education-specialist-administration-planning-policy", label: "Education Specialist in Administration, Planning and Policy, Ed.S"},
{value: "/degrees/online-degree-masters-education-specialist-reading-language", label: "Education Specialist in Reading and Language, Ed.S."},
{value: "/programs/subject/1075-fine-arts-design-and-communications", label: "Fine Arts, Design and Communications"},
{value: "/degrees/online-graduate-certificate-accounting", label: "Graduate Certificate in Accounting"},
{value: "/degrees/online-graduate-certificate-applied-behavior-analysis-bcba", label: "Graduate Certificate in Applied Behavior Analysis: BCBA 5th Edition Coursework Preparation"},
{value: "/degrees/online-graduate-certificate-business-analytics-amherst", label: "Graduate Certificate in Business Analytics - UMass Amherst"},
{value: "/degrees/graduate-certificate-business-analytics", label: "Graduate Certificate in Business Analytics - UMass Boston"},
{value: "/degrees/online-graduate-certificate-business-analytics", label: "Graduate Certificate in Business Analytics - UMass Dartmouth"},
{value: "/degrees/online-graduate-certificate-business-analytics-lowell", label: "Graduate Certificate in Business Analytics - UMass Lowell"},
{value: "/degrees/online-certificate-clinical-pathology", label: "Graduate Certificate in Clinical Pathology"},
{value: "/degrees/online-graduate-certificate-cybersecurity", label: "Graduate Certificate in Cybersecurity"},
{value: "/degrees/online-certificate-domestic-violence-prevention", label: "Graduate Certificate in Domestic Violence Prevention"},
{value: "/degrees/online-graduate-certificate-early-grade-reading-developing-countries", label: "Graduate Certificate in Early Grade Reading in Developing Countries"},
{value: "/degrees/online-certificate-educational-policy", label: "Graduate Certificate in Educational Policy"},
{value: "/degrees/online-graduate-certificate-embedded-systems", label: "Graduate Certificate in Embedded Systems "},
{value: "/degrees/online-certificate-environmental-policy", label: "Graduate Certificate in Environmental Policy "},
{value: "/degrees/online-graduate-certificate-evaluation-assessment", label: "Graduate Certificate in Evaluation and Assessment"},
{value: "/degrees/online-graduate-certificate-finance", label: "Graduate Certificate in Finance"},
{value: "/degrees/online-graduate-certificate-forensic-accounting-amherst", label: "Graduate Certificate in Forensic Accounting"},
{value: "/degrees/online-certificate-forensic-criminology", label: "Graduate Certificate in Forensic Criminology"},
{value: "/degrees/online-certificate-business-foundations-lowell", label: "Graduate Certificate in Foundations of Business"},
{value: "/degrees/online-graduate-certificate-gender-leadership-public-policy", label: "Graduate Certificate in Gender, Leadership, and Public Policy"},
{value: "/degrees/online-certificate-gerontology-aging-services", label: "Graduate Certificate in Gerontology "},
{value: "/degrees/online-graduate-certificate-global-health", label: "Graduate Certificate in Global Health"},
{value: "/degrees/online-certificate-health-informatics", label: "Graduate Certificate in Health Informatics"},
{value: "/degrees/online-certificate-health-management", label: "Graduate Certificate in Health Management"},
{value: "/degrees/graduate-certificate-healthcare-informatics", label: "Graduate Certificate in Healthcare Informatics "},
{value: "/degrees/online-certificate-higher-education-leadership-management", label: "Graduate Certificate in Higher Education Leadership"},
{value: "/degrees/online-graduate-certificate-information-security", label: "Graduate Certificate in Information Security"},
{value: "/degrees/online-certificate-instruction-learning-design", label: "Graduate Certificate in Instructional and Learning Design "},
{value: "/degrees/online-certificate-international-business", label: "Graduate Certificate in International Business"},
{value: "/degrees/online-graduate-certificate-new-venture-creation", label: "Graduate Certificate in New Venture Creation"},
{value: "/degrees/online-graduate-certificate-organizational-leadership", label: "Graduate Certificate in Organizational Leadership"},
{value: "/degrees/online-certificate-plastics-engineering", label: "Graduate Certificate in Plastics Engineering Fundamentals"},
{value: "/degrees/online-graduate-certificate-public-management", label: "Graduate Certificate in Public Management"},
{value: "/degrees/online-certificate-security-studies", label: "Graduate Certificate in Security Studies"},
{value: "/degrees/online-graduate-certificate-supply-chain-management-information-systems", label: "Graduate Certificate in Supply Chain Management and Information Systems"},
{value: "/degrees/online-graduate-certificate-systems-models-management", label: "Graduate Certificate in Systems Models and Management"},
{value: "/degrees/online-graduate-certificate-victim studies", label: "Graduate Certificate in Victim Studies"},
{value: "/programs/subject/147-health-sciences", label: "Health Sciences"},
{value: "/programs/subject/1076-liberal-arts-and-humanities", label: "Liberal Arts and Humanities"},
{value: "/degrees/online-degree-master-vision-studies-orientation-mobility", label: "M.Ed. Vision Studies (Orientation and Mobility)"},
{value: "/degrees/online-degree-master-vision-studies-visual-impairments", label: "M.Ed. Vision Studies (Teachers of Students with Visual Impairments)"},
{value: "/degrees/online-degree-master-vision-studies-rehabilitation-therapy", label: "M.Ed. Vision Studies (Vision Rehabilitation Therapy)"},
{value: "/degrees/online-degree-master-science-education", label: "M.Ed./Ed.S: Science Education Online"},
{value: "/degrees/online-degree-master-criminal-justice", label: "Master of Arts in Criminal Justice"},
{value: "/degrees/online-degree-master-arts-critical-creative-thinking", label: "Master of Arts in Critical and Creative Thinking"},
{value: "/degrees/online-degree-master-history", label: "Master of Arts in History"},
{value: "/degrees/online-degree-master-security-studies-homeland-defense", label: "Master of Arts in Security Studies: Homeland Defense Concentration"},
{value: "/degrees/online-degree-master-industrial-economic-security", label: "Master of Arts in Security Studies: Industrial and Economic Security Concentration"},
{value: "/degrees/online-degree-master-international-security", label: "Master of Arts in Security Studies: International Security Concentration"},
{value: "/degrees/online-degree-master-school-counseling", label: "Master of Education in Counseling"},
{value: "/degrees/online-degree-master-education-curriculum-instruction", label: "Master of Education in Curriculum and Instruction, M.Ed."},
{value: "/degrees/online-degree-masters-behavioral-autism", label: "Master of Education in Curriculum and Instruction: Autism Studies Option"},
{value: "/degrees/online-degree-master-education-science-teachers", label: "Master of Education in Curriculum and Instruction: Science Education Option, M.Ed."},
{value: "/degrees/online-degree-master-educational-administration", label: "Master of Education in Education Administration, M.Ed."},
{value: "/degrees/online-degree-master-education-instructional-design", label: "Master of Education in Instructional Design"},
{value: "/degrees/online-degree-master-education-reading-language", label: "Master of Education in Reading and Language, M.Ed."},
{value: "/degrees/online-degree-master-public-health-nutrition", label: "Master of Public Health in Nutrition"},
{value: "/degrees/online-degree-master-public-health", label: "Master of Public Health in Public Health Practice"},
{value: "/degrees/online-degree-masters-public-policy", label: "Master of Public Policy"},
{value: "/degrees/online-degree-master-public-policy-amherst", label: "Master of Public Policy"},
{value: "/degrees/online-degree-master-clinical-nurse-leader", label: "Master of Science Clinical Nurse Leader"},
{value: "/degrees/online-degree-master-plant-soil-sciences", label: "Master of Science Degree in Plant and Soil Sciences"},
{value: "/degrees/online-master-science-accounting-dartmouth", label: "Master of Science in Accounting"},
{value: "/degrees/online-blended-degree-master-accounting-amherst", label: "Master of Science in Accounting - Isenberg MSA at UMass Amherst - Online MSA"},
{value: "/degrees/online-degree-master-accounting-lowell", label: "Master of Science in Accounting - Manning School of Business at UMass Lowell - Online MSA"},
{value: "/degrees/online-degree-master-business-analytics-amherst", label: "Master of Science in Business & Analytics"},
{value: "/degrees/online-degree-master-business-analytics-lowell", label: "Master of Science in Business Analytics - UMass Lowell"},
{value: "/degrees/online-degree-masters-computer-science", label: "Master of Science in Computer Science"},
{value: "/degrees/online-master-science-engineering-management", label: "Master of Science in Engineering Management - UMass Amherst"},
{value: "/degrees/online-degree-master-engineering-management-lowell", label: "Master of Science in Engineering Management - UMass Lowell"},
{value: "/degrees/online-degree-master-finance", label: "Master of Science in Finance"},
{value: "/degrees/online-degree-master-health-informatics-management", label: "Master of Science in Health Informatics and Management"},
{value: "/degrees/online-degree-masters-healthcare-management", label: "Master of Science in Healthcare Management"},
{value: "/degrees/online-degree-master-information-technology", label: "Master of Science in Information Technology"},
{value: "/degrees/online-degree-master-mental-health-counseling", label: "Master of Science in Mental Health"},
{value: "/degrees/online-degree-masters-science-nursing", label: "Master of Science in Nursing"},
{value: "/degrees/online-degree-master-rehabilitation-counseling", label: "Master of Science in Rehabilitation Counseling"},
{value: "/degrees/online-degree-master-security-studies-critical-infrastructure-protection", label: "Master of Science in Security Studies: Critical Infrastructure Protection Concentration"},
{value: "/degrees/online-degree-master-security-studies-cyber-security", label: "Master of Science in Security Studies: Cybersecurity Concentration"},
{value: "/degrees/online-master-science-technology-management", label: "Master of Science in Technology Management"},
{value: "/degrees/online-degree-master-business-administration-amherst", label: "Master's Degree in Business Administration - Isenberg Online MBA at the University of Massachusetts Amherst"},
{value: "/degrees/online-degree-master-business-administration-lowell", label: "Master's Degree in Business Administration - Online MBA at UMass Lowell"},
{value: "/degrees/online-degree-master-business-administration-dartmouth", label: "Master's Degree in Business Administration – Online MBA at UMass Dartmouth"},
{value: "/degrees/online-degree-master-applied-linguistics", label: "Master's in Applied Linguistics"},
{value: "/degrees/online-degree-master-gerontology", label: "Master's in Gerontology - Management of Aging Services"},
{value: "/degrees/online-degree-master-business-administration-boston", label: "Master’s Degree in Business Administration – Online MBA at UMass Boston"},
{value: "/degrees/online-certificate-new-england-regional-soil-science", label: "New England Regional Soil Science Certificate Program"},
{value: "/degrees/online-certificate-organizing-managing-senior-transportation", label: "Organizing and Managing Senior Transportation Options Certificate"},
{value: "/degrees/online-certificate-orientation-mobility", label: "Orientation and Mobility Certificate"},
{value: "/degrees/online-bachelors-degree-political-science", label: "Political Science Online Degree Program"},
{value: "/degrees/blended-certificate-post-master-nurse-practitioner", label: "Post Master's Nurse Practitioner Certificate"},
{value: "/degrees/online-post-master-psychiatric-mental-health-nurse-practitioner-certificate", label: "Post-Master's Psychiatric Mental Health Nurse Practitioner Certificate (PMHNP) "},
{value: "/degrees/online-project-management", label: "Practical Project Management"},
{value: "/degrees/online-project-risk-management-digital-badge", label: "Project Risk Management"},
{value: "/degrees/online-degree-bachelor-nursing-rn-bs-amherst", label: "RN to BS (Amherst)"},
{value: "/degrees/online-degree-bachelor-nursing-rn-bs-boston", label: "RN to BS (Boston)"},
{value: "/degrees/online-degree-bachelor-nursing-rn-bs-dartmouth", label: "RN to BS in Nursing (Dartmouth)"},
{value: "/programs/subject/1077-science-engineering-and-math", label: "Science, Engineering and Math"},
{value: "/programs/subject/1078-social-and-political-sciences", label: "Social and Political Sciences"},
{value: "/degrees/online-certificate-gerontology", label: "Undergraduate Certificate in Gerontology"},
{value: "/degrees/online-vision-therapy-graduate-certificate", label: "Vision Rehabilitation Therapy Certificate"},
{value: "/degrees/online-degree-bachelor-womens-studies-completion-program", label: "Women's and Gender Studies Online Degree Program"},
{value: "/degrees/online-certificate-women-studies", label: "Women's and Gender Studies Undergraduate Certificate Program"}
];